version: 2

sources:
  - name: raw
    database: USER_DB_BLUEJAY         # or "{{ env_var('DBT_DATABASE') }}"
    schema: raw            # or "{{ env_var('DBT_SCHEMA') }}"
    description: "Schema which stores raw tables (ETL)"
    tables:
      - name: top_tracks
        identifier: TOP_TRACKS
        description: "Raw historical top_tracks data"